name: doctu
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
    auth0_flutter: ^1.2.1
    flutter:
        sdk: flutter
    flutter_riverpod: ^2.3.6
    iconify_flutter: ^0.0.5
    shared_preferences: ^2.2.0
    speech_to_text: ^6.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    fonts:
        - family: GeneralSans
          fonts:
              - asset: fonts/Satoshi-Regular.otf
              - asset: fonts/Satoshi-Bold.otf
                weight: 700
              - asset: fonts/Satoshi-Medium.otf
                weight: 600
    assets:
        - Assets/backgrounds/
        - Assets/Logo/
        - Assets/Blogs/
